### ISSUE TITLE
Building from source fails on Linux

### ISSUE THREAD

**Issue by ChipsSpectre** [rg3dengine/rusty-editor#17]
Hi,

which version of rg3d (I tried 0.17.0) is compatible with the latest version of rusty-editor?

It seems some classes were removed from rg3d: 
```
error[E0432]: unresolved import `rg3d::gui::message::TreeExpansionStrategy`
  --> src/world_outliner.rs:25:26
   |
25 |             TextMessage, TreeExpansionStrategy, TreeMessage, TreeRootMessage, UiMessageData,
   |                          ^^^^^^^^^^^^^^^^^^^^^ no `TreeExpansionStrategy` in `gui::message`
```

**Comment by ChipsSpectre** [comment]
Update: The versions 0.12.0, 0.16.0, 0.18.0 are also not working.

**Comment by ChipsSpectre** [comment]
Update: It is working, if rg3d is placed in a sibling folder.

root/
   rusty-editor/
   rg3d/

This should be mentioned in the README.md.

Which steps can be done to make sure the rusty-editor can be built standalone?

**Comment by mrDIMAS** [comment]
Hi! Sorry, I didn't publish rg3d 0.19 yet, it is compatible with latest rusty-editor. I'll check if I can do that right now, also I'll mention build instructions in the README.md

**Comment by mrDIMAS** [comment]
Should be fixed now.
