### ISSUE TITLE
Unclear error message when saving scene

### ISSUE THREAD

**Issue by gstilwell** [rg3dengine/rusty-editor#28]
The editor gives an error message when saving the scene: "Failed to save scene! Reason: io error: Access is denied. (os error 5)"

I was able to find this workaround by searching in the Discord channel: "You need to type correct name of scene, unfortunately there is no SaveFileSelector widget yet and I'm using FileSelector for this purpose"

A few thoughts as to making the problem more clear in absence of a SaveFileSelector widget:

1) Increase the default width of the FileSelector pop-up so that you can see the entire path and are more likely to notice that there is no filename
2) Append an "untitled.rgs" to the end of the path if no filename is present so the save can still go through
3) Add clarifying text "no filename given" or something of the sort to the error message

**Comment by mrDIMAS** [comment]
I'll try to fix this asap, most likely that I'll just add SaveFile mode for the selector.
