### ISSUE TITLE
Additional Controls for Editor

### ISSUE THREAD

**Issue by d4140n-4h3-1** [rg3dengine/rusty-editor#37]
Rusty Editor seems to lack two controls. Just like **WASD** are used as _directional controls_, there should also be "**Space**" to _rise_ and "**Shift**" to _sink_. 

Additionally, control sensitivity should be a factor. As far as the mouse control goes, I don't see any issues with the way it works.

**Comment by ajmwagar** [comment]
It'd also be nice if the directional controls worked independently from the camera angle, so using the global axes to move around, instead of moving along the local camera axes.
