### ISSUE TITLE
Window cannot be resized on Gnome Wayland.

### ISSUE THREAD

**Issue by IceGuye** [rg3dengine/rusty-editor#57]
Operating System: Fedora 34

RG3D Version: git master

Rusty-editor version: git master

Run the rusty-editor on Gnome Wayland, cannot resize the window.

This issue makes the rusty-editor unusable on Wayland.

Additional information: I also  tried to run the game StationIapetus on Gnome Wayland, similar issue: Window size is not adjustable.

**Comment by mrDIMAS** [comment]
I'm pretty sure that this should be fixed with this PR - https://github.com/rg3dengine/rg3d/pull/204.
